<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>b_T211</name>
   <tag></tag>
   <elementGuidId>7a8e2ea2-2145-4182-9b30-52fa0186243e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='ui-tabpanel-6']/div/div/div/rz-grid/p-datatable/div/div/div/div[3]/div/table/tfoot/tr/td[2]/span/b</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>b</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-star-inserted</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>T:211</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ui-tabpanel-6&quot;)/div[@class=&quot;row ng-star-inserted&quot;]/div[@class=&quot;col-lg-6&quot;]/div[1]/rz-grid[1]/p-datatable[1]/div[@class=&quot;ui-datatable ui-widget ui-datatable-reflow ui-datatable-scrollable&quot;]/div[@class=&quot;ui-datatable-scrollable-wrapper ui-helper-clearfix ng-star-inserted&quot;]/div[@class=&quot;ui-datatable-scrollable-view&quot;]/div[@class=&quot;ui-widget-header ui-datatable-scrollable-footer ng-star-inserted&quot;]/div[@class=&quot;ui-datatable-scrollable-footer-box&quot;]/table[1]/tfoot[@class=&quot;ui-datatable-tfoot&quot;]/tr[@class=&quot;ui-state-default ng-star-inserted&quot;]/td[@class=&quot;ui-state-default ng-star-inserted&quot;]/span[@class=&quot;ui-column-footer ng-star-inserted&quot;]/b[@class=&quot;ng-star-inserted&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ui-tabpanel-6']/div/div/div/rz-grid/p-datatable/div/div/div/div[3]/div/table/tfoot/tr/td[2]/span/b</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Total'])[30]/following::b[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='today'])[1]/preceding::b[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='month'])[1]/preceding::b[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//b</value>
   </webElementXpaths>
</WebElementEntity>
