<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_near_me</name>
   <tag></tag>
   <elementGuidId>d2b9f6ae-a402-48f4-a9eb-a826f4defb9b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='ui-tabpanel-5']/app-tab-dispositivos/div[2]/div/div/rz-grid/p-datatable/div/div/div/div[2]/div/table/tbody/tr/td[5]/span[2]/rz-button/button/i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-button-icon-left fa ng-star-inserted</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>near_me</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ui-tabpanel-5&quot;)/app-tab-dispositivos[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-lg-5&quot;]/div[1]/rz-grid[1]/p-datatable[1]/div[@class=&quot;ui-datatable ui-widget ui-datatable-reflow ui-datatable-scrollable&quot;]/div[@class=&quot;ui-datatable-scrollable-wrapper ui-helper-clearfix ng-star-inserted&quot;]/div[@class=&quot;ui-datatable-scrollable-view&quot;]/div[@class=&quot;ui-datatable-scrollable-body&quot;]/div[@class=&quot;ui-datatable-scrollable-table-wrapper&quot;]/table[1]/tbody[@class=&quot;ui-datatable-data ui-widget-content ui-datatable-hoverable-rows&quot;]/tr[@class=&quot;ng-star-inserted ui-datatable-even ui-state-highlight ui-widget-content&quot;]/td[@class=&quot;ng-star-inserted&quot;]/span[@class=&quot;ui-cell-data ng-star-inserted&quot;]/rz-button[@class=&quot;ng-star-inserted&quot;]/button[@class=&quot;ui-button ui-button-md ui-widget ui-state-default ui-corner-all btn-success ui-button-icon-only&quot;]/i[@class=&quot;ui-button-icon-left fa ng-star-inserted&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ui-tabpanel-5']/app-tab-dispositivos/div[2]/div/div/rz-grid/p-datatable/div/div/div/div[2]/div/table/tbody/tr/td[5]/span[2]/rz-button/button/i</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ruta'])[2]/following::i[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Estado'])[2]/following::i[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Editar'])[1]/preceding::i[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='tecnico'])[3]/preceding::i[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//rz-button/button/i</value>
   </webElementXpaths>
</WebElementEntity>
