<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_search</name>
   <tag></tag>
   <elementGuidId>96df68da-2068-40b8-8f02-217252d73ab2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='ui-tabpanel-6']/div/div/div/rz-grid/p-datatable/div/div/div/div/div/table/thead/tr/th[2]/div/div/label/i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>material-icons</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>search</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ui-tabpanel-6&quot;)/div[@class=&quot;row ng-star-inserted&quot;]/div[@class=&quot;col-lg-6&quot;]/div[1]/rz-grid[1]/p-datatable[1]/div[@class=&quot;ui-datatable ui-widget ui-datatable-reflow ui-datatable-scrollable&quot;]/div[@class=&quot;ui-datatable-scrollable-wrapper ui-helper-clearfix ng-star-inserted&quot;]/div[@class=&quot;ui-datatable-scrollable-view&quot;]/div[@class=&quot;ui-widget-header ui-datatable-scrollable-header&quot;]/div[@class=&quot;ui-datatable-scrollable-header-box&quot;]/table[1]/thead[@class=&quot;ui-datatable-thead&quot;]/tr[@class=&quot;ui-state-default ng-star-inserted&quot;]/th[@class=&quot;ng-star-inserted ui-state-default ui-unselectable-text ui-sortable-column&quot;]/div[@class=&quot;ui-cell-filter ng-star-inserted&quot;]/div[@class=&quot;ui-cell-filter-content&quot;]/label[1]/i[@class=&quot;material-icons&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ui-tabpanel-6']/div/div/div/rz-grid/p-datatable/div/div/div/div/div/table/thead/tr/th[2]/div/div/label/i</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Total'])[23]/following::i[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='search'])[27]/following::i[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tecnico'])[2]/preceding::i[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/rz-grid/p-datatable/div/div/div/div/div/table/thead/tr/th[2]/div/div/label/i</value>
   </webElementXpaths>
</WebElementEntity>
