<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_1</name>
   <tag></tag>
   <elementGuidId>70be3d75-b44c-447b-8797-cfd2ae2e39f0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='ui-tabpanel-6']/div/div[2]/rz-card/div/div/rz-scheduler/div/p-schedule/div/div[2]/div/table/tbody/tr/td/div/div/div/div[2]/table/thead/tr/td</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fc-day-top fc-sun fc-past</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-date</name>
      <type>Main</type>
      <value>2019-09-01</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>1</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ui-tabpanel-6&quot;)/div[@class=&quot;row ng-star-inserted&quot;]/div[@class=&quot;col-lg-6&quot;]/rz-card[1]/div[@class=&quot;card&quot;]/div[@class=&quot;row align-items-center&quot;]/rz-scheduler[1]/div[1]/p-schedule[1]/div[@class=&quot;undefined fc ui-widget fc-ltr&quot;]/div[@class=&quot;fc-view-container&quot;]/div[@class=&quot;fc-view fc-month-view fc-basic-view&quot;]/table[1]/tbody[@class=&quot;fc-body&quot;]/tr[1]/td[@class=&quot;ui-widget-content&quot;]/div[@class=&quot;fc-scroller fc-day-grid-container&quot;]/div[@class=&quot;fc-day-grid fc-unselectable&quot;]/div[@class=&quot;fc-row fc-week ui-widget-content&quot;]/div[@class=&quot;fc-content-skeleton&quot;]/table[1]/thead[1]/tr[1]/td[@class=&quot;fc-day-top fc-sun fc-past&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ui-tabpanel-6']/div/div[2]/rz-card/div/div/rz-scheduler/div/p-schedule/div/div[2]/div/table/tbody/tr/td/div/div/div/div[2]/table/thead/tr/td</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sat'])[1]/following::td[9]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Fri'])[1]/following::td[9]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Created with Highcharts 6.2.0'])[2]/preceding::td[119]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Total'])[34]/preceding::td[119]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/table/thead/tr/td</value>
   </webElementXpaths>
</WebElementEntity>
